services:
  - type: web
    name: telegram-flask-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: PORT
        value: 10000
